version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: yourusername
      POSTGRES_DB: pentest_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
